---
title: "usefulR_narratives"
output: html_document
date: "2023-08-10"
---




```{r}
library(car)
library(psych)
library(reshape)
library(PupillometryR)
library(plyr); library(dplyr)
library(tidyselect)
library(tidyr)
library(stringr)
library(lmerTest)
library(gghalves)
# source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
# file.sources = list.files(c("/Users/h/Documents/projects_local/cue_expectancy/scripts/step02_R/utils"),
#                           pattern="*.R", 
#                           full.names=TRUE, 
#                           ignore.case=TRUE)
# sapply(file.sources,source,.GlobalEnv)
```
```{r}
meanSummary <- function(data, group, dv) {
    library(plyr)
    z <- plyr::ddply(data, group, .fun = function(xx) {
        c(
            mean_per_sub = mean(xx[, dv], na.rm = TRUE),
            sd = sd(xx[, dv], na.rm = TRUE)
        )
    })
    return(z)
}
```
```{r}
normDataWithin <- function(data = NULL, idvar, measurevar, betweenvars = NULL,
                           na.rm = FALSE, .drop = TRUE) {
#   """
#   Norms the data within specified groups in a data frame;
#   it normalizes each subject (identified by idvar),
#   within each group specified by betweenvars.

#   Parameters
#   ----------
#   data:
#         a data frame.
#   idvar:
#         the column name that identifies each subject (or matched subjects)
#   measurevar:
#         the column name that contains the variable to be summariezed
#   betweenvars:
#         a vector containing that are between-subjects column names
#   na.rm:
#         a boolean that indicates whether to ignore NA's
#   """
  library(plyr)

  # Measure var on left, idvar + between vars on right of formula.
  data.subjMean <- ddply(data, c(idvar, betweenvars),
    .drop = .drop,
    .fun = function(xx, col, na.rm) {
      c(subjMean = mean(xx[, col], na.rm = na.rm))
    },
    measurevar,
    na.rm
  )

  # Put the subject means with original data
  data <- merge(data, data.subjMean)

  # Get the normalized data in a new column
  measureNormedVar <- paste(measurevar, "_norm", sep = "")
  data[, measureNormedVar] <- data[, measurevar] - data[, "subjMean"] +
    mean(data[, measurevar], na.rm = na.rm)

  # Remove this subject mean column
  data$subjMean <- NULL

  return(data)
}
```

```{r}
plot_halfrainclouds_onefactor <- function(subjectwise, groupwise, iv,
                                      subjectwise_mean, group_mean, se, subject,
                                      ggtitle, title, xlab, ylab, taskname, ylim,
                                      w, h, dv_keyword, color, save_fname) {
  g <- ggplot(
    data = subjectwise,
    aes(
      y = .data[[subjectwise_mean]],
      x = factor(.data[[iv]]),
      fill = factor(.data[[iv]])
    )
  ) +
    coord_cartesian(ylim = ylim, expand = TRUE) +
    # geom_flat_violin(
    #   aes(fill = factor(.data[[iv]])),
    #   position = position_nudge(x = .1, y = 0),
    #   adjust = 1.5, trim = FALSE, alpha = .3, colour = NA
    # ) +

    geom_half_violin(
      aes(fill = factor(.data[[iv]])),
      side = 'r',
      position = 'dodge',
      adjust = 1.5,
      trim = FALSE,
      alpha = .3,
      colour = NA
    ) +

    # geom_line(
    #   data = subjectwise,
    #   aes(
    #     group = .data[[subject]],
    #     y = .data[[subjectwise_mean]],
    #     x = as.numeric(.data[[iv]]) - .15,
    #     fill = factor(.data[[iv]])
    #   ),
    #   linetype = "solid", color = "grey", alpha = .3
    # ) +
    # geom_point(
    #   aes(
    #     x = as.numeric(.data[[iv]]) - .15,
    #     y = .data[[subjectwise_mean]],
    #     color = factor(.data[[iv]])
    #   ),
    #   position = position_jitter(width = .05),
    #   size = 1, alpha = 0.8, shape = 20
    # ) +

  geom_line(data = subjectwise,
    aes(
      group = .data[[subject]],
      x = as.numeric(as.factor(.data[[iv]])) - .15 ,
      y = .data[[subjectwise_mean]],
      fill = factor(.data[[iv]])
      ),
    linetype = "solid",
    color = "grey",
    alpha = .3) +

  geom_point(
    aes(
      # group = .data[[subject]],
      x = as.numeric(as.factor(.data[[iv]])) - .15 ,
      y = .data[[subjectwise_mean]],
      color = factor(.data[[iv]])
    ),
    position = position_jitter(width = .05),
    size = 2,
    alpha = 0.7,
  ) + 
    # geom_boxplot(
    #   aes(
    #     x = .data[[iv]],
    #     y = .data[[subjectwise_mean]],
    #     fill = .data[[iv]]
    #   ),
    #   outlier.shape = NA, alpha = 0.8, width = .1, colour = "black"
    # ) +

    geom_half_boxplot(
      data = subjectwise,
      aes(x = .data[[iv]],
          y = .data[[subjectwise_mean]],
          fill = .data[[iv]]),
      side = "r",
      outlier.shape = NA,
      alpha = 0.8,
      width = .1,
      notch = FALSE,
      notchwidth = 0,
      varwidth = FALSE,
      colour = "black",
      errorbar.draw = FALSE
    ) +

    geom_errorbar(
      data = groupwise,
      aes(
        x = as.numeric(.data[[iv]]) + .1,
        y = as.numeric(.data[[group_mean]]),
        colour = factor(.data[[iv]]),
        ymin = .data[[group_mean]] - .data[[se]],
        ymax = .data[[group_mean]] + .data[[se]]
      ), width = .05
    ) +


    # legend stuff ________________________________________________________ # nolint
    expand_limits(x = 2.8) +
    #guides(fill = "none") +
    guides(color = "none") +
    guides(fill = guide_legend(title = title)) +
    scale_fill_manual(values = color) +
    scale_color_manual(values = color) +
    ggtitle(ggtitle) +
    xlab(xlab) +
    ylab(ylab) +
    theme_bw()
  ggsave(save_fname, width = w, height = h)
  return(g)
}
```

```{r}
## define function to calculate summary statistics
## Summarizes data.
## Gives count, mean, standard deviation, standard error of the mean, and
## confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
##   adapted from Ryan Hope's function:
##   https://www.rdocumentation.org/packages/Rmisc/versions/1.5/topics/summarySE




# summarySE function
summarySE <- function(data = NULL, measurevar, groupvars = NULL, na.rm = FALSE,
                      conf.interval = .95, .drop = TRUE) {
  library(plyr)

  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function(x, na.rm = FALSE) {
    if (na.rm) {
      sum(!is.na(x))
    } else {
      length(x)
    }
  }

  # This does the summary. For each group's data frame, return a vector with
  # N, mean, median, and sd

  datac <- plyr::ddply(data, groupvars, .drop=.drop,
                   .fun = function(xx, col) {
                       c(N      = length2(xx[[col]], na.rm=na.rm),
                         mean   = mean(xx[[col]], na.rm=na.rm),
                         median = median(xx[[col]], na.rm=na.rm),
                         sd      = sd(xx[[col]], na.rm=na.rm)
                       )
                   },
                   measurevar
  )

  # Rename the "mean" and "median" columns
 datac <- plyr::rename(datac, c("mean" = paste(measurevar, "_mean", sep = "")))
 datac <- plyr::rename(datac, c("median" = paste(measurevar, "_median", sep = "")))

 datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval:
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval / 2 + .5, datac$N - 1)
  datac$ci <- datac$se * ciMult

  return(datac)
}

```
```{r}
summarySEwithin <- function(data = NULL, measurevar, betweenvars = NULL, withinvars = NULL,
                            idvar = NULL, na.rm = FALSE, conf.interval = .95, .drop = TRUE) {
#   """
#   Summarizes data, handling within-subjects variables
#   by removing inter-subject variability.
#   It will still work if there are no within-S variables.
#   Gives count, un-normed mean, normed mean (with same between-group mean),
#   standard deviation, standard error of the mean, and confidence interval.
#   If there are within-subject variables,
#   calculate adjusted values using method from Morey (2008).

#   Parameters
#   ----------
#   data:
#       a data frame.
#   measurevar:
#       the name of a column that contains the variable to be summariezed
#   betweenvars:
#       a vector containing names of columns that are between-subjects variables
#   withinvars:
#       a vector containing names of columns that are within-subjects variables
#   idvar:
#       the name of a column that identifies each subject (or matched subjects)
#   na.rm:
#       a boolean that indicates whether to ignore NA's
#   conf.interval:
#       the percent range of the confidence interval (default is 95%)
#       Ensure that the betweenvars and withinvars are factors
#   """
    library(raincloudplots)
    factorvars <- vapply(data[, c(betweenvars, withinvars), drop = FALSE],
        FUN = is.factor, FUN.VALUE = logical(1)
    )

    if (!all(factorvars)) {
        nonfactorvars <- names(factorvars)[!factorvars]
        message(
            "Automatically converting the following non-factors to factors: ",
            paste(nonfactorvars, collapse = ", ")
        )
        data[nonfactorvars] <- lapply(data[nonfactorvars], factor)
    }

    # Get the means from the un-normed data
    datac <- summarySE(data, measurevar,
        groupvars = c(betweenvars, withinvars),
        na.rm = na.rm, conf.interval = conf.interval, .drop = .drop
    )

    # Drop all the unused columns (these will be calculated with normed data)
    datac$sd <- NULL
    datac$se <- NULL
    datac$ci <- NULL

    # Norm each subject's data
    ndata <- normDataWithin(data, idvar, measurevar, betweenvars, na.rm, .drop = .drop)

    # This is the name of the new column
    measurevar_n <- paste(measurevar, "_norm", sep = "")

    # Collapse the normed data - now we can treat between and within vars the same
    ndatac <- summarySE(ndata, measurevar_n,
        groupvars = c(betweenvars, withinvars),
        na.rm = na.rm, conf.interval = conf.interval, .drop = .drop
    )

    # Apply correction from Morey (2008) to the standard error and confidence interval
    #  Get the product of the number of conditions of within-S variables
    nWithinGroups <- prod(vapply(ndatac[, withinvars, drop = FALSE],
        FUN = nlevels,
        FUN.VALUE = numeric(1)
    ))
    correctionFactor <- sqrt(nWithinGroups / (nWithinGroups - 1))

    # Apply the correction factor
    ndatac$sd <- ndatac$sd * correctionFactor
    ndatac$se <- ndatac$se * correctionFactor
    ndatac$ci <- ndatac$ci * correctionFactor

    # Combine the un-normed means with the normed results
    df <- merge(datac, ndatac)
    return(df)
}
```




```{r}
# load in the dataframe
# create contrasts for pain vs non-pain runs
# summary statistics for each subject
# group wise statistics
# plot
```


```{r}
# df <- read.csv("/Users/h/Documents/summer/summer_RA/fdmean_run_type.tsv")
narrativesdf <- read.table(file = "~/Desktop/summer_RA/data/merged_task-narratives.tsv", sep = '\t', header = TRUE)
facesdf <- read.table(file = "~/Desktop/summer_RA/data/merged_task-faces.tsv", sep = '\t', header = TRUE)
fractionaldf <- read.table(file = "~/Desktop/summer_RA/data/merged_task-fractional.tsv", sep = '\t', header = TRUE)
socialdf <- read.table(file="~/Desktop/summer_RA/data/merged_task-social.tsv", sep= '\t', header = TRUE)
alignvideodf <- read.table(file="~/Desktop/summer_RA/data/merged_task-alignvideo.tsv", sep= '\t', header = TRUE)
shortvideodf <- read.table(file="~/Desktop/summer_RA/data/merged_task-shortvideo.tsv", sep= '\t', header = TRUE)
#adding a task column
facesdf$task<- "faces"
narrativesdf$task<-"narratives"
fractionaldf$task<- "fractional"
socialdf$task<- "social"
alignvideodf$task<- "alignvideo"
shortvideodf$task<- "shortvideo"
# would need to make new df for other tasks
fdmeandf<- rbind(facesdf, narrativesdf, fractionaldf, socialdf, alignvideodf, shortvideodf)
#need to call new data frame fdmeandf to make code generic even though there is nothing to do with the fd mean
# creating a new data frame from multiple data frames in order to add to one plot
# make sure to add the different task when rbinding
```

```{r}
# contrast code 1 linear

# fdmeandf$PAIN_NOPAIN[fdmeandf$run_type == "pain"] <- 0.5
# fdmeandf$PAIN_NOPAIN[fdmeandf$run_type == "vicarious"] <- -0.5
# fdmeandf$PAIN_NOPAIN[fdmeandf$run_type == "cognitive"] <- -0.5
# df <- fdmeandf %>% drop_na(PAIN_NOPAIN)
```

```{r}
df <-fdmeandf
df$sub_factor <- factor(df$sub)
# model.fdmean <- lmer(fd_mean ~ PAIN_NOPAIN + (1|sub_factor), data=df)
```

```{r}
# summary(model.fdmean)
```

```{r}
# df$run_name[df$run_type == "pain"] <- "pain"
# df$run_name[df$run_type == "vicarious"] <- "non-pain"
# df$run_name[df$run_type == "cognitive"] <- "non-pain"

# df$pain_ordered <- factor(
#         df$run_name,
#         levels = c("non-pain", "pain")
#     )

# start grabbing sub-wise means

subject <- "sub_factor"
model_iv <- "task"
dv <- "globalsignal_mean"
subjectwise <- meanSummary(df,c(subject, model_iv), dv)

groupwise <- summarySEwithin(
  data=subjectwise,
  measurevar = "mean_per_sub",
  withinvars = c(model_iv),
  idvar = subject
)
```

```{r}
analysis_dir <- "/Users/owencollins/Desktop"
# combined_se_calc_cooksd <-NPSstimcue_groupwise
# calculate mean and se
sub_mean <- "mean_per_sub"
group_mean <- "mean_per_sub_norm_mean"
se <- "se"
subject <- "sub_factor"
ggtitle <- paste( dv)
title <- paste( dv)
xlab <- ""
ylab <- "Global Signal Mean (a.u)"

dv_keyword <- "fdmean"
if (any(startsWith(dv_keyword, c("expect", "Expect")))) {
  color <- c("#1B9E77", "#D95F02")
} else {
  color <- c("#4575B4", "#D73027", "#1B9E77", "#D95F02","orchid", "ivory4")
} # if keyword starts with
plot_savefname <- file.path(
  analysis_dir,
  paste(
    "raincloud_qc-", dv_keyword, "_", as.character(Sys.Date()), "_cooksd.png",
    sep = ""
  )
)

# ----------------------------------------------------------------------
#                            raincloudplots
# ----------------------------------------------------------------------
# TODO: 
# * change the range of the figure
# * change the x-axis
# * drop the NA conditions
# * change theme
# * adjust the box plots

ylim <- c(1000,6500)
# check bounds
taskname = "all"
w <- 10; h <- 5
g <- plot_halfrainclouds_onefactor(
  subjectwise,
  groupwise,
  model_iv,
  sub_mean,
  group_mean,
  se,
  subject,
  ggtitle,
  title,
  xlab,
  ylab,
  taskname,
  ylim,
  w,
  h,
  dv_keyword,
  color,
  plot_savefname
)
g <- g + theme_bw() + theme_classic()
print(g)


# k <- plot_lineplot_twofactor(NPSstimcue_groupwise,
#                         iv1 = "stim_ordered", iv2 = "cue_ordered",
#                         mean = "mean_per_sub_norm_mean", error = "se",
#                         color = c("pain" = "red",
#                                   "non-pain" = "gray"))
#                                   # "med" = "orange",

```

```{r}
df_example <- tibble(x = c(1,2,NA), y = c("a", NA, "b"))
df_example %>% drop_na(x)
```


